version: '3'
services:
  frontend:
    build: frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - $RC_FRONTEND_PORT:3000
    environment:
      - RC_BACKEND_PORT
  json-server:
    build: json-server
    volumes:
      - ./json-server:/app
      - /app/node_modules
    ports:
      - $RC_BACKEND_PORT:3000
