version: '3'
services:
  frontend:
    build: frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - $RC_FRONTEND_PORT:3000
    environment:
      - RC_BACKEND_PORT
    networks:
      - default
  simple-server:
    build: simple-server
    volumes:
      - ./simple-server:/app
      - /app/node_modules
    ports:
      - $RC_BACKEND_PORT:3000
    environment:
      - RC_MONGO_HOST=mongo
      - RC_MONGO_DB=other-db
    networks:
      - default
      - backend
  mongo:
    image: mongo
    networks:
      - backend

networks:
  backend:
