version: '3'
services:
  backend:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - RC_MONGO_HOST=mongo
      - RC_MONGO_DB=other-db
    networks:
      - default
      - backend
  mongo:
    image: mongo
    networks:
      - backend

networks:
  backend:
