// flow-typed signature: f25e4ea5c8c85b7e7353305a5822b2a7
// flow-typed version: <<STUB>>/customize-cra_v^0.1.0-beta6/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'customize-cra'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'customize-cra' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'customize-cra/index' {
  declare module.exports: $Exports<'customize-cra'>;
}
declare module 'customize-cra/index.js' {
  declare module.exports: $Exports<'customize-cra'>;
}
